services:
  node-gate-1:
    image: gate1.0
    container_name: node-gate-1
    ports:
      - "8001:8001"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./excels:/app/excels
    networks:
      - ldl_network

networks:
  ldl_network:
    external: true