services:
  ssdb-admin-1:
    image: jhao104/ssdb-admin
    container_name: ssdb-manager-1
    ports:
      - "5000:5000"
    environment:
      DB_CONFIG: "shard1.ssdb1:8888"
    networks:
      - ldl_network

#  ssdb-admin-2:
#    image: jhao104/ssdb-admin
#    container_name: ssdb-manager-1
#    ports:
#      - "5002:5000"
#    environment:
#      DB_CONFIG: "ssdb2:18888"
#    networks:
#      - ldl_network

networks:
  ldl_network:
    driver: bridge