services:
  ssdb1:
    image: tsl0922/ssdb:latest
    container_name: ldl.ssdb1
    command: ssdb-server /data/ssdb.conf
    environment:
      - SSDB_AUTH="123"  # 部分镜像支持
    volumes:
      - ./storage/ssdb:/data
    ports:
      - "18888:18888"
    networks:
      - ldl_network

networks:
  ldl_network:
    external: true