services:
  websockify:
    image: novnc/websockify:latest
    # 使用多进程或调整缓冲区（如果版本支持）
    command: ["80", "192.168.1.102:17001"]
    ulimits:
      nofile:
        soft: 65536
        hard: 6553
    networks:
      - ldl_network
networks:
  ldl_network:
    driver: bridge
