services:
  ssdb1:
    image: tsl0922/ssdb:latest
    container_name: ldl.ssdb1
    environment:
      - SSDB_AUTH="123"  # 部分镜像支持
    volumes:
      - ./storage/ssdb:/var/lib/ssdb
    ports:
      - "8888:8888"
    networks:
      - ldl_network

networks:
  ldl_network:
    driver: bridge