// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v6.33.4
// source: game.proto

package pbGo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 匹配请求 1001
type StartMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType     uint32      `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"`        // 房间类型,对应配置表roomId
	HeroId       uint32      `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"`            // 选择的人物
	ItemInfoList []*ItemInfo `protobuf:"bytes,3,rep,name=itemInfoList,proto3" json:"itemInfoList,omitempty"` //选择的道具
}

func (x *StartMatchReq) Reset() {
	*x = StartMatchReq{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchReq) ProtoMessage() {}

func (x *StartMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchReq.ProtoReflect.Descriptor instead.
func (*StartMatchReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *StartMatchReq) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *StartMatchReq) GetHeroId() uint32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *StartMatchReq) GetItemInfoList() []*ItemInfo {
	if x != nil {
		return x.ItemInfoList
	}
	return nil
}

type StartMatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartMatchResp) Reset() {
	*x = StartMatchResp{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResp) ProtoMessage() {}

func (x *StartMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResp.ProtoReflect.Descriptor instead.
func (*StartMatchResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

// 匹配信息推送 1002
type MatchInfoPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType       uint32        `protobuf:"varint,1,opt,name=roomType,proto3" json:"roomType,omitempty"` // 对应配置表id
	PlayerInfoList []*PlayerInfo `protobuf:"bytes,2,rep,name=playerInfoList,proto3" json:"playerInfoList,omitempty"`
}

func (x *MatchInfoPush) Reset() {
	*x = MatchInfoPush{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoPush) ProtoMessage() {}

func (x *MatchInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoPush.ProtoReflect.Descriptor instead.
func (*MatchInfoPush) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *MatchInfoPush) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *MatchInfoPush) GetPlayerInfoList() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfoList
	}
	return nil
}

// 取消匹配 1003
type CancelMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelMatchReq) Reset() {
	*x = CancelMatchReq{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReq) ProtoMessage() {}

func (x *CancelMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReq.ProtoReflect.Descriptor instead.
func (*CancelMatchReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

type CancelMatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelMatchResp) Reset() {
	*x = CancelMatchResp{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResp) ProtoMessage() {}

func (x *CancelMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResp.ProtoReflect.Descriptor instead.
func (*CancelMatchResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

// 竞拍请求 1004
type BetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetInfo   []*ItemInfo `protobuf:"bytes,1,rep,name=betInfo,proto3" json:"betInfo,omitempty"`
	Operation int32       `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"` // 操作类型，0:竞拍，1弃权
}

func (x *BetReq) Reset() {
	*x = BetReq{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetReq) ProtoMessage() {}

func (x *BetReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetReq.ProtoReflect.Descriptor instead.
func (*BetReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *BetReq) GetBetInfo() []*ItemInfo {
	if x != nil {
		return x.BetInfo
	}
	return nil
}

func (x *BetReq) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

type BetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
}

func (x *BetResp) Reset() {
	*x = BetResp{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResp) ProtoMessage() {}

func (x *BetResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResp.ProtoReflect.Descriptor instead.
func (*BetResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *BetResp) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 轮数信息推送 1005
type RoundInfoPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndTimeOut       int64               `protobuf:"varint,1,opt,name=endTimeOut,proto3" json:"endTimeOut,omitempty"`            //本局结束倒计时，时间戳毫秒
	RoundIndex       uint32              `protobuf:"varint,2,opt,name=roundIndex,proto3" json:"roundIndex,omitempty"`            //第几轮
	IsFinish         bool                `protobuf:"varint,3,opt,name=isFinish,proto3" json:"isFinish,omitempty"`                //是否结束
	ChangeScreenInfo *ScreenInfo         `protobuf:"bytes,4,opt,name=changeScreenInfo,proto3" json:"changeScreenInfo,omitempty"` //上局的所有的信息
	HintList         []*Hint             `protobuf:"bytes,6,rep,name=hintList,proto3" json:"hintList,omitempty"`                 // 提示信息,包含词条，人物的
	SettlementInfo   *RoomSettlementInfo `protobuf:"bytes,7,opt,name=SettlementInfo,proto3" json:"SettlementInfo,omitempty"`     //结算信息，如果 isFinish=true 时有值
}

func (x *RoundInfoPush) Reset() {
	*x = RoundInfoPush{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundInfoPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundInfoPush) ProtoMessage() {}

func (x *RoundInfoPush) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundInfoPush.ProtoReflect.Descriptor instead.
func (*RoundInfoPush) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *RoundInfoPush) GetEndTimeOut() int64 {
	if x != nil {
		return x.EndTimeOut
	}
	return 0
}

func (x *RoundInfoPush) GetRoundIndex() uint32 {
	if x != nil {
		return x.RoundIndex
	}
	return 0
}

func (x *RoundInfoPush) GetIsFinish() bool {
	if x != nil {
		return x.IsFinish
	}
	return false
}

func (x *RoundInfoPush) GetChangeScreenInfo() *ScreenInfo {
	if x != nil {
		return x.ChangeScreenInfo
	}
	return nil
}

func (x *RoundInfoPush) GetHintList() []*Hint {
	if x != nil {
		return x.HintList
	}
	return nil
}

func (x *RoundInfoPush) GetSettlementInfo() *RoomSettlementInfo {
	if x != nil {
		return x.SettlementInfo
	}
	return nil
}

// 使用道具请求 1006
type UseItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *ItemInfo `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"` //使用的道具
}

func (x *UseItemReq) Reset() {
	*x = UseItemReq{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemReq) ProtoMessage() {}

func (x *UseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemReq.ProtoReflect.Descriptor instead.
func (*UseItemReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *UseItemReq) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

type UseItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemInfoList     []*ItemInfo `protobuf:"bytes,1,rep,name=itemInfoList,proto3" json:"itemInfoList,omitempty"`         //剩余的道具
	ChangeScreenInfo *ScreenInfo `protobuf:"bytes,2,opt,name=changeScreenInfo,proto3" json:"changeScreenInfo,omitempty"` //新变化的信息
	HintList         []*Hint     `protobuf:"bytes,3,rep,name=hintList,proto3" json:"hintList,omitempty"`                 // 提示信息,包含词条，人物的
}

func (x *UseItemResp) Reset() {
	*x = UseItemResp{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResp) ProtoMessage() {}

func (x *UseItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResp.ProtoReflect.Descriptor instead.
func (*UseItemResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *UseItemResp) GetItemInfoList() []*ItemInfo {
	if x != nil {
		return x.ItemInfoList
	}
	return nil
}

func (x *UseItemResp) GetChangeScreenInfo() *ScreenInfo {
	if x != nil {
		return x.ChangeScreenInfo
	}
	return nil
}

func (x *UseItemResp) GetHintList() []*Hint {
	if x != nil {
		return x.HintList
	}
	return nil
}

// 提示信息
type Hint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               // 提示id,对应 ability的id
	HintType  uint32 `protobuf:"varint,2,opt,name=hintType,proto3" json:"hintType,omitempty"`   // 0：人物提示，1：词条提示
	Value     uint64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`         //总价值,平均价值,的值等,已经扩大1000分比
	ValueType uint32 `protobuf:"varint,4,opt,name=valueType,proto3" json:"valueType,omitempty"` //0：没有值，1：总价值,2:平均价值等,的值等，已经扩大1000分比
}

func (x *Hint) Reset() {
	*x = Hint{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *Hint) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hint) GetHintType() uint32 {
	if x != nil {
		return x.HintType
	}
	return 0
}

func (x *Hint) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Hint) GetValueType() uint32 {
	if x != nil {
		return x.ValueType
	}
	return 0
}

// 屏幕信息
type ScreenInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GridList       []*Grid       `protobuf:"bytes,1,rep,name=GridList,proto3" json:"GridList,omitempty"` //品质变化
	AllGoods       []*Goods      `protobuf:"bytes,2,rep,name=allGoods,proto3" json:"allGoods,omitempty"`
	PlayerInfoList []*PlayerInfo `protobuf:"bytes,3,rep,name=playerInfoList,proto3" json:"playerInfoList,omitempty"` //玩家竞拍信息
}

func (x *ScreenInfo) Reset() {
	*x = ScreenInfo{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenInfo) ProtoMessage() {}

func (x *ScreenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenInfo.ProtoReflect.Descriptor instead.
func (*ScreenInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *ScreenInfo) GetGridList() []*Grid {
	if x != nil {
		return x.GridList
	}
	return nil
}

func (x *ScreenInfo) GetAllGoods() []*Goods {
	if x != nil {
		return x.AllGoods
	}
	return nil
}

func (x *ScreenInfo) GetPlayerInfoList() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfoList
	}
	return nil
}

// 物品信息
type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId      uint32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`           // 产品id
	Index       uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`             // 位置
	ShowAll     uint32 `protobuf:"varint,3,opt,name=showAll,proto3" json:"showAll,omitempty"`         //图片是否全显示效果，0:隐藏，回合数index，等于当前回合数则是当前局变化的，小于则是之前局变化的,0代表不显示，回合:1~5,
	ShowContour uint32 `protobuf:"varint,4,opt,name=showContour,proto3" json:"showContour,omitempty"` //轮廓是否显示效果，0:隐藏回合数index，等于当前回合数则是当前局变化的，小于则是之前局变化的,0代表不显示，回合:1~5,
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *Goods) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Goods) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Goods) GetShowAll() uint32 {
	if x != nil {
		return x.ShowAll
	}
	return 0
}

func (x *Goods) GetShowContour() uint32 {
	if x != nil {
		return x.ShowContour
	}
	return 0
}

// 一个格子信息
type Grid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexId     uint32 `protobuf:"varint,1,opt,name=indexId,proto3" json:"indexId,omitempty"`         // 位置
	ShowQuality uint32 `protobuf:"varint,2,opt,name=showQuality,proto3" json:"showQuality,omitempty"` //品质是否显示效果，回合数index，等于当前回合数则是当前局变化的，小于则是之前局变化的,0代表不显示，回合:1~5,
	QualityType uint32 `protobuf:"varint,3,opt,name=qualityType,proto3" json:"qualityType,omitempty"` //品质是否显示效果，回合数index，等于当前回合数则是当前局变化的，小于则是之前局变化的,0代表不显示，回合:1~5,
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *Grid) GetIndexId() uint32 {
	if x != nil {
		return x.IndexId
	}
	return 0
}

func (x *Grid) GetShowQuality() uint32 {
	if x != nil {
		return x.ShowQuality
	}
	return 0
}

func (x *Grid) GetQualityType() uint32 {
	if x != nil {
		return x.QualityType
	}
	return 0
}

// 房间结算信息
type RoomSettlementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfo *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"` //结算玩家
	Expenses   *ItemInfo   `protobuf:"bytes,2,opt,name=expenses,proto3" json:"expenses,omitempty"`     //花费
	Profit     *ItemInfo   `protobuf:"bytes,3,opt,name=profit,proto3" json:"profit,omitempty"`         //利润
}

func (x *RoomSettlementInfo) Reset() {
	*x = RoomSettlementInfo{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSettlementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSettlementInfo) ProtoMessage() {}

func (x *RoomSettlementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSettlementInfo.ProtoReflect.Descriptor instead.
func (*RoomSettlementInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *RoomSettlementInfo) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *RoomSettlementInfo) GetExpenses() *ItemInfo {
	if x != nil {
		return x.Expenses
	}
	return nil
}

func (x *RoomSettlementInfo) GetProfit() *ItemInfo {
	if x != nil {
		return x.Profit
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x65,
	0x72, 0x6f, 0x1a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0d,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72,
	0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49,
	0x64, 0x12, 0x32, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x67, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x50, 0x0a, 0x06, 0x62, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x28, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x62, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x0a, 0x08, 0x68, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x68, 0x69, 0x6e, 0x74,
	0x52, 0x08, 0x68, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0xa7,
	0x01, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32,
	0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68,
	0x65, 0x72, 0x6f, 0x2e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x26, 0x0a, 0x08, 0x68, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x52, 0x08,
	0x68, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x66, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x68, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x99, 0x01, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x26, 0x0a, 0x08, 0x47, 0x72, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x47, 0x72, 0x69, 0x64, 0x52, 0x08, 0x47,
	0x72, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x68, 0x65, 0x72, 0x6f,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x12, 0x3a, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x05,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x68, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x22,
	0x64, 0x0a, 0x04, 0x47, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x65, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x74, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x47, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_proto_goTypes = []any{
	(*StartMatchReq)(nil),      // 0: hero.startMatchReq
	(*StartMatchResp)(nil),     // 1: hero.startMatchResp
	(*MatchInfoPush)(nil),      // 2: hero.MatchInfoPush
	(*CancelMatchReq)(nil),     // 3: hero.cancelMatchReq
	(*CancelMatchResp)(nil),    // 4: hero.cancelMatchResp
	(*BetReq)(nil),             // 5: hero.betReq
	(*BetResp)(nil),            // 6: hero.betResp
	(*RoundInfoPush)(nil),      // 7: hero.roundInfoPush
	(*UseItemReq)(nil),         // 8: hero.useItemReq
	(*UseItemResp)(nil),        // 9: hero.useItemResp
	(*Hint)(nil),               // 10: hero.hint
	(*ScreenInfo)(nil),         // 11: hero.screenInfo
	(*Goods)(nil),              // 12: hero.goods
	(*Grid)(nil),               // 13: hero.Grid
	(*RoomSettlementInfo)(nil), // 14: hero.RoomSettlementInfo
	(*ItemInfo)(nil),           // 15: item.itemInfo
	(*PlayerInfo)(nil),         // 16: player.playerInfo
}
var file_game_proto_depIdxs = []int32{
	15, // 0: hero.startMatchReq.itemInfoList:type_name -> item.itemInfo
	16, // 1: hero.MatchInfoPush.playerInfoList:type_name -> player.playerInfo
	15, // 2: hero.betReq.betInfo:type_name -> item.itemInfo
	16, // 3: hero.betResp.playerInfo:type_name -> player.playerInfo
	11, // 4: hero.roundInfoPush.changeScreenInfo:type_name -> hero.screenInfo
	10, // 5: hero.roundInfoPush.hintList:type_name -> hero.hint
	14, // 6: hero.roundInfoPush.SettlementInfo:type_name -> hero.RoomSettlementInfo
	15, // 7: hero.useItemReq.item:type_name -> item.itemInfo
	15, // 8: hero.useItemResp.itemInfoList:type_name -> item.itemInfo
	11, // 9: hero.useItemResp.changeScreenInfo:type_name -> hero.screenInfo
	10, // 10: hero.useItemResp.hintList:type_name -> hero.hint
	13, // 11: hero.screenInfo.GridList:type_name -> hero.Grid
	12, // 12: hero.screenInfo.allGoods:type_name -> hero.goods
	16, // 13: hero.screenInfo.playerInfoList:type_name -> player.playerInfo
	16, // 14: hero.RoomSettlementInfo.playerInfo:type_name -> player.playerInfo
	15, // 15: hero.RoomSettlementInfo.expenses:type_name -> item.itemInfo
	15, // 16: hero.RoomSettlementInfo.profit:type_name -> item.itemInfo
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_player_proto_init()
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
